version: '3.7'
services:

  sqs-admin:
    image:  paco0512/sqs-admin
    ports:
      - "3999:3999"
    environment:
      SQS_ENDPOINT_URL: "http://localstack:4566"
      AWS_REGION: "eu-central-1"
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:0.14.2
    ports:
      - "4566:4566"
    environment:
      SERVICES: sqs
      EXTRA_CORS_ALLOWED_ORIGINS: "*"
