version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "github"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "npm"

  - package-ecosystem: "gomod"
    directory: "/server"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "go"