name: Frontend tests
on: push

defaults:
  run:
    working-directory: frontend

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: prepare
        run: yarn install
      - name: test
        run: yarn test
